<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Table des evenements du calendrier, saisis depuis le back-office.
 *
 * Ecrite a la main : make:migration exige doctrine/dbal ^4.5, pas encore
 * publie (voir la contrainte doctrine/orm dans composer.json). Le SQL vient
 * de doctrine:schema:update --dump-sql, restreint a cette seule table.
 */
final class Version20260908090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cree la table des evenements du calendrier.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE event (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(150) NOT NULL,
                type VARCHAR(20) NOT NULL,
                starts_at DATE NOT NULL,
                ends_at DATE DEFAULT NULL,
                time_label VARCHAR(60) NOT NULL,
                description TEXT DEFAULT NULL,
                location VARCHAR(150) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        // La page d'accueil et la purge nocturne filtrent toutes deux sur la
        // date : c'est le seul acces qui merite un index.
        $this->addSql('CREATE INDEX idx_event_starts_at ON event (starts_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE event');
    }
}
