<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Table des bulletins d'adhesion deposes depuis le site.
 *
 * Ecrite a la main : make:migration exige doctrine/dbal ^4.5, pas encore
 * publie (voir le commentaire sur la contrainte doctrine/orm dans
 * composer.json). Le SQL provient de doctrine:schema:update --dump-sql,
 * restreint a la seule table de cette migration.
 */
final class Version20260904170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return "Cree la table des bulletins d'adhesion deposes en ligne.";
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE membership_application (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                last_name VARCHAR(100) NOT NULL,
                first_name VARCHAR(100) NOT NULL,
                birth_date DATE NOT NULL,
                address VARCHAR(255) DEFAULT NULL,
                postal_code VARCHAR(10) NOT NULL,
                city VARCHAR(100) NOT NULL,
                phone VARCHAR(30) DEFAULT NULL,
                email VARCHAR(180) NOT NULL,
                membership_type VARCHAR(20) NOT NULL,
                principal_member_name VARCHAR(200) DEFAULT NULL,
                philibert_consent BOOLEAN NOT NULL,
                image_rights_refused BOOLEAN NOT NULL,
                statutes_accepted BOOLEAN NOT NULL,
                rules_accepted BOOLEAN NOT NULL,
                guardian_last_name VARCHAR(100) DEFAULT NULL,
                guardian_first_name VARCHAR(100) DEFAULT NULL,
                guardian_email VARCHAR(180) DEFAULT NULL,
                signature_place VARCHAR(100) NOT NULL,
                signature_name VARCHAR(200) NOT NULL,
                submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        // La liste du back-office trie par date de depot decroissante.
        $this->addSql('CREATE INDEX IDX_MEMBERSHIP_APPLICATION_SUBMITTED_AT ON membership_application (submitted_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE membership_application');
    }
}
